name: Build libsmooth.so (arm64-v8a)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: কোড ক্লোন করুন
        uses: actions/checkout@v3

      - name: Android NDK সেটআপ করুন
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: CMake দিয়ে কম্পাইল করুন
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: আউটপুট `.so` ফাইল প্যাক করুন
        run: |
          mkdir -p output/zygisk/arm64-v8a
          cp build/libzygisk.so output/zygisk/arm64-v8a/libsmooth.so
          cd output && zip -r libsmooth_arm64-v8a.zip zygisk

      - name: `.zip` ফাইল আপলোড করুন
        uses: actions/upload-artifact@v3
        with:
          name: libsmooth_arm64-v8a
          path: output/libsmooth_arm64-v8a.zip
